/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationUpdateRequestBody
 */
export interface AuthenticationUpdateRequestBody {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationUpdateRequestBody
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationUpdateRequestBody
     */
    oldPassword: string;
}

/**
 * Check if a given object implements the AuthenticationUpdateRequestBody interface.
 */
export function instanceOfAuthenticationUpdateRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "oldPassword" in value;

    return isInstance;
}

export function AuthenticationUpdateRequestBodyFromJSON(json: any): AuthenticationUpdateRequestBody {
    return AuthenticationUpdateRequestBodyFromJSONTyped(json, false);
}

export function AuthenticationUpdateRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationUpdateRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'oldPassword': json['oldPassword'],
    };
}

export function AuthenticationUpdateRequestBodyToJSON(value?: AuthenticationUpdateRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'oldPassword': value.oldPassword,
    };
}

