/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationEmailRegisterRequestBody
 */
export interface AuthenticationEmailRegisterRequestBody {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailRegisterRequestBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailRegisterRequestBody
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailRegisterRequestBody
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationEmailRegisterRequestBody
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticationEmailRegisterRequestBody interface.
 */
export function instanceOfAuthenticationEmailRegisterRequestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthenticationEmailRegisterRequestBodyFromJSON(json: any): AuthenticationEmailRegisterRequestBody {
    return AuthenticationEmailRegisterRequestBodyFromJSONTyped(json, false);
}

export function AuthenticationEmailRegisterRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationEmailRegisterRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'password': json['password'],
    };
}

export function AuthenticationEmailRegisterRequestBodyToJSON(value?: AuthenticationEmailRegisterRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'password': value.password,
    };
}

