/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardsPostBody
 */
export interface CardsPostBody {
    /**
     * 
     * @type {string}
     * @memberof CardsPostBody
     */
    postalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardsPostBody
     */
    sourceId: string;
    /**
     * 
     * @type {string}
     * @memberof CardsPostBody
     */
    verificationToken?: string | null;
}

/**
 * Check if a given object implements the CardsPostBody interface.
 */
export function instanceOfCardsPostBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sourceId" in value;

    return isInstance;
}

export function CardsPostBodyFromJSON(json: any): CardsPostBody {
    return CardsPostBodyFromJSONTyped(json, false);
}

export function CardsPostBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardsPostBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'sourceId': json['sourceId'],
        'verificationToken': !exists(json, 'verificationToken') ? undefined : json['verificationToken'],
    };
}

export function CardsPostBodyToJSON(value?: CardsPostBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postalCode': value.postalCode,
        'sourceId': value.sourceId,
        'verificationToken': value.verificationToken,
    };
}

