/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemEntity } from './ItemEntity';
import {
    ItemEntityFromJSON,
    ItemEntityFromJSONTyped,
    ItemEntityToJSON,
} from './ItemEntity';

/**
 * 
 * @export
 * @interface CategoryEntity
 */
export interface CategoryEntity {
    /**
     * 
     * @type {string}
     * @memberof CategoryEntity
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CategoryEntity
     */
    moaOrdinal?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryEntity
     */
    moaEnabled?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CategoryEntity
     */
    name?: string | null;
    /**
     * 
     * @type {Array<ItemEntity>}
     * @memberof CategoryEntity
     */
    items?: Array<ItemEntity> | null;
}

/**
 * Check if a given object implements the CategoryEntity interface.
 */
export function instanceOfCategoryEntity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryEntityFromJSON(json: any): CategoryEntity {
    return CategoryEntityFromJSONTyped(json, false);
}

export function CategoryEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'moaOrdinal': !exists(json, 'moaOrdinal') ? undefined : json['moaOrdinal'],
        'moaEnabled': !exists(json, 'moaEnabled') ? undefined : json['moaEnabled'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(ItemEntityFromJSON)),
    };
}

export function CategoryEntityToJSON(value?: CategoryEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'moaOrdinal': value.moaOrdinal,
        'moaEnabled': value.moaEnabled,
        'name': value.name,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(ItemEntityToJSON)),
    };
}

