/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerPatchBody
 */
export interface CustomerPatchBody {
    /**
     * 
     * @type {string}
     * @memberof CustomerPatchBody
     */
    preferredLocationId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPatchBody
     */
    preferredSquareCardId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerPatchBody
     */
    mailNotifications?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerPatchBody
     */
    messageNotifications?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerPatchBody
     */
    pushNotifications?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPatchBody
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPatchBody
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPatchBody
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the CustomerPatchBody interface.
 */
export function instanceOfCustomerPatchBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CustomerPatchBodyFromJSON(json: any): CustomerPatchBody {
    return CustomerPatchBodyFromJSONTyped(json, false);
}

export function CustomerPatchBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPatchBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'preferredLocationId': !exists(json, 'preferredLocationId') ? undefined : json['preferredLocationId'],
        'preferredSquareCardId': !exists(json, 'preferredSquareCardId') ? undefined : json['preferredSquareCardId'],
        'mailNotifications': !exists(json, 'mailNotifications') ? undefined : json['mailNotifications'],
        'messageNotifications': !exists(json, 'messageNotifications') ? undefined : json['messageNotifications'],
        'pushNotifications': !exists(json, 'pushNotifications') ? undefined : json['pushNotifications'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    };
}

export function CustomerPatchBodyToJSON(value?: CustomerPatchBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'preferredLocationId': value.preferredLocationId,
        'preferredSquareCardId': value.preferredSquareCardId,
        'mailNotifications': value.mailNotifications,
        'messageNotifications': value.messageNotifications,
        'pushNotifications': value.pushNotifications,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'phoneNumber': value.phoneNumber,
    };
}

