/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FulfillmentStatusEnum = {
    Proposed: 'PROPOSED',
    Reserved: 'RESERVED',
    Prepared: 'PREPARED',
    Completed: 'COMPLETED',
    Canceled: 'CANCELED',
    Failed: 'FAILED'
} as const;
export type FulfillmentStatusEnum = typeof FulfillmentStatusEnum[keyof typeof FulfillmentStatusEnum];


export function FulfillmentStatusEnumFromJSON(json: any): FulfillmentStatusEnum {
    return FulfillmentStatusEnumFromJSONTyped(json, false);
}

export function FulfillmentStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillmentStatusEnum {
    return json as FulfillmentStatusEnum;
}

export function FulfillmentStatusEnumToJSON(value?: FulfillmentStatusEnum | null): any {
    return value as any;
}

