/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemsPatchBody
 */
export interface ItemsPatchBody {
    /**
     * 
     * @type {string}
     * @memberof ItemsPatchBody
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ItemsPatchBody
     */
    moaOrdinal?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ItemsPatchBody
     */
    moaEnabled?: boolean | null;
}

/**
 * Check if a given object implements the ItemsPatchBody interface.
 */
export function instanceOfItemsPatchBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ItemsPatchBodyFromJSON(json: any): ItemsPatchBody {
    return ItemsPatchBodyFromJSONTyped(json, false);
}

export function ItemsPatchBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemsPatchBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'moaOrdinal': !exists(json, 'moaOrdinal') ? undefined : json['moaOrdinal'],
        'moaEnabled': !exists(json, 'moaEnabled') ? undefined : json['moaEnabled'],
    };
}

export function ItemsPatchBodyToJSON(value?: ItemsPatchBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'moaOrdinal': value.moaOrdinal,
        'moaEnabled': value.moaEnabled,
    };
}

