/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemPatchBody
 */
export interface ItemPatchBody {
    /**
     * 
     * @type {number}
     * @memberof ItemPatchBody
     */
    moaOrdinal?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ItemPatchBody
     */
    moaEnabled?: boolean | null;
}

/**
 * Check if a given object implements the ItemPatchBody interface.
 */
export function instanceOfItemPatchBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemPatchBodyFromJSON(json: any): ItemPatchBody {
    return ItemPatchBodyFromJSONTyped(json, false);
}

export function ItemPatchBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemPatchBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'moaOrdinal': !exists(json, 'moaOrdinal') ? undefined : json['moaOrdinal'],
        'moaEnabled': !exists(json, 'moaEnabled') ? undefined : json['moaEnabled'],
    };
}

export function ItemPatchBodyToJSON(value?: ItemPatchBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'moaOrdinal': value.moaOrdinal,
        'moaEnabled': value.moaEnabled,
    };
}

