/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddressEntity } from './AddressEntity';
import {
    AddressEntityFromJSON,
    AddressEntityFromJSONTyped,
    AddressEntityToJSON,
} from './AddressEntity';
import type { BusinessHoursPeriodEntity } from './BusinessHoursPeriodEntity';
import {
    BusinessHoursPeriodEntityFromJSON,
    BusinessHoursPeriodEntityFromJSONTyped,
    BusinessHoursPeriodEntityToJSON,
} from './BusinessHoursPeriodEntity';

/**
 * 
 * @export
 * @interface LocationEntity
 */
export interface LocationEntity {
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LocationEntity
     */
    moaOrdinal?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof LocationEntity
     */
    moaEnabled?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof LocationEntity
     */
    isMain: boolean;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LocationEntity
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof LocationEntity
     */
    longitude?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    timezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    languageCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    businessName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    websiteUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    businessEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    twitterUsername?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    instagramUsername?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    facebookUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    logoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    posBackgroundUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    mcc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationEntity
     */
    fullFormatLogoUrl?: string | null;
    /**
     * 
     * @type {Array<BusinessHoursPeriodEntity>}
     * @memberof LocationEntity
     */
    businessHours?: Array<BusinessHoursPeriodEntity> | null;
    /**
     * 
     * @type {AddressEntity}
     * @memberof LocationEntity
     */
    address?: AddressEntity | null;
}

/**
 * Check if a given object implements the LocationEntity interface.
 */
export function instanceOfLocationEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isMain" in value;

    return isInstance;
}

export function LocationEntityFromJSON(json: any): LocationEntity {
    return LocationEntityFromJSONTyped(json, false);
}

export function LocationEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'moaOrdinal': !exists(json, 'moaOrdinal') ? undefined : json['moaOrdinal'],
        'moaEnabled': !exists(json, 'moaEnabled') ? undefined : json['moaEnabled'],
        'isMain': json['isMain'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'timezone': !exists(json, 'timezone') ? undefined : json['timezone'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'languageCode': !exists(json, 'languageCode') ? undefined : json['languageCode'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'businessName': !exists(json, 'businessName') ? undefined : json['businessName'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'websiteUrl': !exists(json, 'websiteUrl') ? undefined : json['websiteUrl'],
        'businessEmail': !exists(json, 'businessEmail') ? undefined : json['businessEmail'],
        'twitterUsername': !exists(json, 'twitterUsername') ? undefined : json['twitterUsername'],
        'instagramUsername': !exists(json, 'instagramUsername') ? undefined : json['instagramUsername'],
        'facebookUrl': !exists(json, 'facebookUrl') ? undefined : json['facebookUrl'],
        'logoUrl': !exists(json, 'logoUrl') ? undefined : json['logoUrl'],
        'posBackgroundUrl': !exists(json, 'posBackgroundUrl') ? undefined : json['posBackgroundUrl'],
        'mcc': !exists(json, 'mcc') ? undefined : json['mcc'],
        'fullFormatLogoUrl': !exists(json, 'fullFormatLogoUrl') ? undefined : json['fullFormatLogoUrl'],
        'businessHours': !exists(json, 'businessHours') ? undefined : (json['businessHours'] === null ? null : (json['businessHours'] as Array<any>).map(BusinessHoursPeriodEntityFromJSON)),
        'address': !exists(json, 'address') ? undefined : AddressEntityFromJSON(json['address']),
    };
}

export function LocationEntityToJSON(value?: LocationEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'moaOrdinal': value.moaOrdinal,
        'moaEnabled': value.moaEnabled,
        'isMain': value.isMain,
        'name': value.name,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'description': value.description,
        'phoneNumber': value.phoneNumber,
        'status': value.status,
        'timezone': value.timezone,
        'country': value.country,
        'languageCode': value.languageCode,
        'currency': value.currency,
        'businessName': value.businessName,
        'type': value.type,
        'websiteUrl': value.websiteUrl,
        'businessEmail': value.businessEmail,
        'twitterUsername': value.twitterUsername,
        'instagramUsername': value.instagramUsername,
        'facebookUrl': value.facebookUrl,
        'logoUrl': value.logoUrl,
        'posBackgroundUrl': value.posBackgroundUrl,
        'mcc': value.mcc,
        'fullFormatLogoUrl': value.fullFormatLogoUrl,
        'businessHours': value.businessHours === undefined ? undefined : (value.businessHours === null ? null : (value.businessHours as Array<any>).map(BusinessHoursPeriodEntityToJSON)),
        'address': AddressEntityToJSON(value.address),
    };
}

