/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StatisticsOutput } from './StatisticsOutput';
import {
    StatisticsOutputFromJSON,
    StatisticsOutputFromJSONTyped,
    StatisticsOutputToJSON,
} from './StatisticsOutput';

/**
 * 
 * @export
 * @interface OrdersStatisticsResponse
 */
export interface OrdersStatisticsResponse {
    /**
     * 
     * @type {number}
     * @memberof OrdersStatisticsResponse
     */
    count?: number | null;
    /**
     * 
     * @type {StatisticsOutput}
     * @memberof OrdersStatisticsResponse
     */
    moneyAmount?: StatisticsOutput | null;
    /**
     * 
     * @type {StatisticsOutput}
     * @memberof OrdersStatisticsResponse
     */
    moneyAppFeeAmount?: StatisticsOutput | null;
    /**
     * 
     * @type {StatisticsOutput}
     * @memberof OrdersStatisticsResponse
     */
    moneyServiceChargeAmount?: StatisticsOutput | null;
    /**
     * 
     * @type {StatisticsOutput}
     * @memberof OrdersStatisticsResponse
     */
    moneyTaxAmount?: StatisticsOutput | null;
    /**
     * 
     * @type {StatisticsOutput}
     * @memberof OrdersStatisticsResponse
     */
    moneyTipAmount?: StatisticsOutput | null;
}

/**
 * Check if a given object implements the OrdersStatisticsResponse interface.
 */
export function instanceOfOrdersStatisticsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrdersStatisticsResponseFromJSON(json: any): OrdersStatisticsResponse {
    return OrdersStatisticsResponseFromJSONTyped(json, false);
}

export function OrdersStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersStatisticsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'moneyAmount': !exists(json, 'moneyAmount') ? undefined : StatisticsOutputFromJSON(json['moneyAmount']),
        'moneyAppFeeAmount': !exists(json, 'moneyAppFeeAmount') ? undefined : StatisticsOutputFromJSON(json['moneyAppFeeAmount']),
        'moneyServiceChargeAmount': !exists(json, 'moneyServiceChargeAmount') ? undefined : StatisticsOutputFromJSON(json['moneyServiceChargeAmount']),
        'moneyTaxAmount': !exists(json, 'moneyTaxAmount') ? undefined : StatisticsOutputFromJSON(json['moneyTaxAmount']),
        'moneyTipAmount': !exists(json, 'moneyTipAmount') ? undefined : StatisticsOutputFromJSON(json['moneyTipAmount']),
    };
}

export function OrdersStatisticsResponseToJSON(value?: OrdersStatisticsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'moneyAmount': StatisticsOutputToJSON(value.moneyAmount),
        'moneyAppFeeAmount': StatisticsOutputToJSON(value.moneyAppFeeAmount),
        'moneyServiceChargeAmount': StatisticsOutputToJSON(value.moneyServiceChargeAmount),
        'moneyTaxAmount': StatisticsOutputToJSON(value.moneyTaxAmount),
        'moneyTipAmount': StatisticsOutputToJSON(value.moneyTipAmount),
    };
}

