/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderEntity } from './OrderEntity';
import {
    OrderEntityFromJSON,
    OrderEntityFromJSONTyped,
    OrderEntityToJSON,
} from './OrderEntity';

/**
 * 
 * @export
 * @interface OrdersPaginatedResponse
 */
export interface OrdersPaginatedResponse {
    /**
     * 
     * @type {number}
     * @memberof OrdersPaginatedResponse
     */
    count: number;
    /**
     * 
     * @type {Array<OrderEntity>}
     * @memberof OrdersPaginatedResponse
     */
    data?: Array<OrderEntity> | null;
    /**
     * 
     * @type {number}
     * @memberof OrdersPaginatedResponse
     */
    pages: number;
}

/**
 * Check if a given object implements the OrdersPaginatedResponse interface.
 */
export function instanceOfOrdersPaginatedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "pages" in value;

    return isInstance;
}

export function OrdersPaginatedResponseFromJSON(json: any): OrdersPaginatedResponse {
    return OrdersPaginatedResponseFromJSONTyped(json, false);
}

export function OrdersPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersPaginatedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(OrderEntityFromJSON)),
        'pages': json['pages'],
    };
}

export function OrdersPaginatedResponseToJSON(value?: OrdersPaginatedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(OrderEntityToJSON)),
        'pages': value.pages,
    };
}

