/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripePostCheckoutBody
 */
export interface StripePostCheckoutBody {
    /**
     * 
     * @type {string}
     * @memberof StripePostCheckoutBody
     */
    successUrl: string;
    /**
     * 
     * @type {string}
     * @memberof StripePostCheckoutBody
     */
    cancelUrl: string;
    /**
     * 
     * @type {string}
     * @memberof StripePostCheckoutBody
     */
    stripePriceId: string;
}

/**
 * Check if a given object implements the StripePostCheckoutBody interface.
 */
export function instanceOfStripePostCheckoutBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "successUrl" in value;
    isInstance = isInstance && "cancelUrl" in value;
    isInstance = isInstance && "stripePriceId" in value;

    return isInstance;
}

export function StripePostCheckoutBodyFromJSON(json: any): StripePostCheckoutBody {
    return StripePostCheckoutBodyFromJSONTyped(json, false);
}

export function StripePostCheckoutBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripePostCheckoutBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'successUrl': json['successUrl'],
        'cancelUrl': json['cancelUrl'],
        'stripePriceId': json['stripePriceId'],
    };
}

export function StripePostCheckoutBodyToJSON(value?: StripePostCheckoutBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'successUrl': value.successUrl,
        'cancelUrl': value.cancelUrl,
        'stripePriceId': value.stripePriceId,
    };
}

