/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPatchBody
 */
export interface UserPatchBody {
    /**
     * 
     * @type {string}
     * @memberof UserPatchBody
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPatchBody
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPatchBody
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPatchBody
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPatchBody
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the UserPatchBody interface.
 */
export function instanceOfUserPatchBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserPatchBodyFromJSON(json: any): UserPatchBody {
    return UserPatchBodyFromJSONTyped(json, false);
}

export function UserPatchBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPatchBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'language': !exists(json, 'language') ? undefined : json['language'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    };
}

export function UserPatchBodyToJSON(value?: UserPatchBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'firstName': value.firstName,
        'language': value.language,
        'lastName': value.lastName,
        'phoneNumber': value.phoneNumber,
    };
}

