/* tslint:disable */
/* eslint-disable */
/**
 * MyOrderApp Square API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VariationEntity
 */
export interface VariationEntity {
    /**
     * 
     * @type {string}
     * @memberof VariationEntity
     */
    id?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof VariationEntity
     */
    moaEnabled?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof VariationEntity
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VariationEntity
     */
    ordinal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VariationEntity
     */
    priceMoneyAmount?: number | null;
}

/**
 * Check if a given object implements the VariationEntity interface.
 */
export function instanceOfVariationEntity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VariationEntityFromJSON(json: any): VariationEntity {
    return VariationEntityFromJSONTyped(json, false);
}

export function VariationEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariationEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'moaEnabled': !exists(json, 'moaEnabled') ? undefined : json['moaEnabled'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'ordinal': !exists(json, 'ordinal') ? undefined : json['ordinal'],
        'priceMoneyAmount': !exists(json, 'priceMoneyAmount') ? undefined : json['priceMoneyAmount'],
    };
}

export function VariationEntityToJSON(value?: VariationEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'moaEnabled': value.moaEnabled,
        'name': value.name,
        'ordinal': value.ordinal,
        'priceMoneyAmount': value.priceMoneyAmount,
    };
}

